### ISSUE TITLE
API 15のデバイスで、電源挿抜時に落ちてしまう

### ISSUE THREAD

**Issue by Mossuru777** [changami/BatteryIsReady#3]
電源挿抜後に、OSからイベント通知されるタイミングで落ちてしまいます。
- 現象発生環境
  - Samsung GALAXY SII WiMAX ISW11SC (SIMなし)
  - Android 4.0.4 (API 15)
- 現象発生時ログ

``` adb
07-30 02:38:43.692    7311-7311/com.changami.app.batteryisready E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start receiver com.changami.app.batteryisready.broadcasts.PowerConnectionReceiver: android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2138)
            at android.app.ActivityThread.access$1500(ActivityThread.java:128)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4516)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:991)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
            at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:132)
            at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:126)
            at com.changami.app.batteryisready.broadcasts.PowerConnectionReceiver.onReceive(PowerConnectionReceiver.java:18)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2131)
            at android.app.ActivityThread.access$1500(ActivityThread.java:128)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4516)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:991)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by changami** [comment]
ご報告ありがとうございました！
